server:
  port: 8761 # Eureka Web service port

spring:
  application:
    name: discoveryservice # microservice ?? ID


eureka:
  client:
    # ?? ??? ??? ?? ??, ?????? ?? ???? ?? ?? ?? ??? false
    register-with-eureka: false
    fetch-registry: false